### PR TITLE
Refactor minor issues: contextLogger, defer, Test() func

### PR DESCRIPTION
**Pull request by plutov**
- contextLogger to group same Fields in 3 places.
 - defer should be called after err check of os.Open().
 - Test() function doesn't allow to run tests like `go test ./...` and panics.
 - Rename Sirupsen to sirupsen, as it's a correct path.

### CODE REVIEW

**Comment by plutov** [comment]
@frapposelli Travis CI build is failing because of timeout, can you please check if it works on master branch?

**Comment by frapposelli** [comment]
Hi @plutov and thanks for the PR!

Looks like the problem is triggered on case-sensitive filesystems, the `vendor/github.com/Sirupsen` directory should be committed as lowercase in the branch as well.

**Comment by plutov** [comment]
@frapposelli I got it, I didn't see that vendor is committed to repo. Why do we need it as we use dep with fixed dependencies?

**Comment by plutov** [comment]
Also, error happened before I committed change in Sirupsen.

**Comment by frapposelli** [comment]
It's a way to ensure a consistent build, dependencies are pinned with `dep` to ensure a known working state, but there is no guarantee those versions will always be available.

**Comment by frapposelli** [comment]
Looks like a problem in the CI env, most tests are green so I'm confident in merging as is.

**Comment by frapposelli** [comment]
Thank you! 🎉

**Pull request merged**
